name: Flutter Worklow
env:
  FLUTTER_VERSION: "stable"

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  buildJDK:

#set up a JDK version
      - uses: actions/setup-java@v1
        with:
          java-version: '12.x'
          
  buildFlutter:  
#set up flutter
      - name: Installing Flutter
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: '2.0.5

       - name: npm install, and test
        run: 
          npm install
          npm test
       - name: install dependencies 
        run: flutter pub get
      - name: Running tests
        run: flutter test --no-pub
        
 builduploadArtifact:     
      - name: Archive Production Artifact
        uses: actions/upload-artifact@master
        with:
          name: dist
          path: dist
          
     #for Dart PL        
      - uses: dart-lang/setup-dart@9a04e6d73cca37bd455e0608d7e5092f881fd603
          

