name: Final Workflow
on:
  push:
    branches: [dev ]
  pull_request:
    branches: [ dev ]
    
# Define the Jobs we want to run as part of this Workflow
jobs:
  # Define our build and test Job
   build-and-test: 
   
    # We want to run this Job on an Ubuntu VM 
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository code using V1 of the standard checkout Action
      - uses: actions/checkout@v2
      - uses: dart-lang/setup-dart@9a04e6d73cca37bd455e0608d7e5092f881fd603
       
       # Use the standard Java Action to setup Java 
      - uses: actions/setup-java@v1
        with:
          # we want the latest Java 12
          java-version: '12.x'

        # Use the community Action to install Flutter
      - uses: subosito/flutter-action@v1
        with:
          # we want the stable channel
          channel: 'stable'  
          
        # Get flutter packages
      - run: flutter pub get
       # Analyze our Dart code
      #- run: flutter analyze
      # Run our tests
      #- run: flutter test
      
   #runs unit tests located in the project.  (- name: Assemble app debug APK)  
     # - name: Run Unit tests
      #  path: 
       # run: bash ./gradlew test --stacktrace
        #env:
         #  WAP_API_KEY: ${{ secrets.WAP_API_KEY }}   
      
    # Upload generated apk to the artifacts.
      - uses: actions/upload-artifact@v2
        with: 
         name: release-apk
         path: build/app/outputs/apk/release/app-release.apk  
         
         
   Firebase:
       runs-on: ubuntu-latest
       
       name: Run UI tests with Firebase Test Lab
       steps:
          - uses: actions/checkout@v1
          - name: Download app APK  #download all the artifacts we generated in the previous step
            uses: actions/download-artifact@v1
            with:
              name: app-debug
             # path: build/app/outputs/apk/debug/app-debug.apk  
     
