name: Final Workflow
on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]
    
# Define the Jobs we want to run as part of this Workflow
jobs:
  # Define our build and test Job
   build-and-test: 
   
    # We want to run this Job on an Ubuntu VM 
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository code using V1 of the standard checkout Action
      - uses: actions/checkout@v2
      - uses: dart-lang/setup-dart@9a04e6d73cca37bd455e0608d7e5092f881fd603
       
       # Use the standard Java Action to setup Java 
      - uses: actions/setup-java@v1
        with:
          # we want the latest Java 12
          java-version: '12.x'

        # Use the community Action to install Flutter
      - uses: subosito/flutter-action@v1
        with:
          # we want the stable channel
          channel: 'stable'  
          
        # Get flutter packages
      - run: flutter pub get
       # Analyze our Dart code
     # - run: flutter analyze
      # Run our tests
      - run: flutter test

android-integration-test:
    name: run integration test on Android emulator
    runs-on: ubuntu-latest
    # TODO(tianhaoz95): re-enable this once integration test works.
    strategy:
      #set of different configurations of the virtual environment.
      matrix:
        api-level: [29]
        target: [default]
    needs: flutter_test
    steps:
      - uses: actions/checkout@v1
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: '2.2.2'
          channel: 'stable'
      - name: Run Flutter Driver tests
        #GitHub Action for installing, configuring and running Android Emulators (work only Mac OS)
        #https://github.com/ReactiveCircus/android-emulator-runner
        uses: reactivecircus/android-emulator-runner@v1
        with:
          api-level: ${{ matrix.api-level }}
          target: ${{ matrix.target }}
          arch: x86_64
          profile: Nexus 6
          script: flutter drive --driver=test_driver/integration_test_driver.dart --target=integration_test/app_test.dart