name: Final Workflow

on:
  push:
    branches: [dev]
  pull_request:
    branches: [dev]

jobs:
  build_android:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup Java
        uses: actions/setup-java@v1
        with:
          java-version: "12.x"
      - name: Setup Flutter
        uses: subosito/flutter-action@v1
        with:
          flutter-version: "1.22.5"
      - name: Format files
        run: flutter format --set-exit-if-changed .
      - name: Analyze code
        run: flutter analyze
             flutter pub outdated
             
      - name: Run tests
        run: flutter test

