name: Final Workflow
on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]
    
# Define the Jobs we want to run as part of this Workflow
jobs:
  # Define our build and test Job
   unit-test: 
    name: Unit tests
    # We want to run this Job on an Ubuntu VM 
    runs-on: ${{ matrix.os }}
    strategy: 
      matrix:
        os: [ubuntu-18.04, windows-2019, macgos-10.15]
   
    steps:
     
      # Checkout the repository code using V1 of the standard checkout Action
      - uses: actions/checkout@v2
   
       # Use the standard Java Action to setup Java 
      - uses: actions/setup-java@v1
        with:
          # we want the latest Java 12
          java-version: '12.x'
         
      - name: Set up Flutter 
        # Use the community Action to install Flutter
      - uses: subosito/flutter-action@v1
        with:
          # we want the stable channel
          channel: 'stable'  
  
        # Get flutter packages
      - run: flutter pub get
       # Analyze our Dart code
     # - run: flutter analyze
      # Run our tests
      - name: Run Flutter tests
      - run: flutter test


  
